<a href="https://colab.research.google.com/github/lumunge/100-days-of-code/blob/master/Python/NumpyUfuncs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""Numpy Ufuncs - functions for operating on ndarray(numpy array)
Ufuncs implement vectorrization to ndarray
Vectorization involves replacing loops with array expressions
Vectorized operations in numpy assign internal looping to optimized C code,
this is cleaner and faster"""

In [38]:
import numpy as np
from math import log

In [ ]:
"""ufunc argumets:
  where - define place for operations
  dtype - define return type
  out - output array"""

In [43]:
# Arithmetic

a = np.random.randint(10, size=10)
b = np.random.randint(10, size=10)
print(a)
print(b)

print(np.add(a, b)) # add two ndarray

print(np.subtract(a, b)) # subtract two ndarray

print(np.multiply(a, b)) # multiply two ndarray

print(np.divide(a, b)) # divide

print(np.power(a, b)) # b power a

print(np.mod(a, b)) # a mod b

print(np.divmod(a, b)) # quotient, mod

print(np.absolute(a)) # absolute values


[4 1 1 1 8 6 2 2 0 1]
[0 0 7 0 7 3 9 6 2 3]
[ 4  1  8  1 15  9 11  8  2  4]
63
[ 4  1 -6  1  1  3 -7 -4 -2 -2]
[ 0  0  7  0 56 18 18 12  0  3]
[       inf        inf 0.14285714        inf 1.14285714 2.
 0.22222222 0.33333333 0.         0.33333333]
[      1       1       1       1 2097152     216     512      64       0
       1]
[0 0 1 0 1 0 2 2 0 1]
(array([0, 0, 0, 0, 1, 2, 0, 0, 0, 0]), array([0, 0, 1, 0, 1, 0, 2, 2, 0, 1]))
[4 1 1 1 8 6 2 2 0 1]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in remainder
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: divide by zero encountered in divmod


In [11]:
# Custom ufuncs - frompyfunc()
"""frompyfunc() arguments
  function - function name
  input - number of input arrays
  output - number of output arrays"""

def prod(a, b):
  return a * b

prod = np.frompyfunc(prod, 2, 1)

print(prod(a, b))

# print(type(np.prod)) -> check if prod is a ufunc

[49 28 8 15 24 0 6 12 27 35]


In [30]:
# Rounding decimals
z = np.random.uniform(low=1.0, high=9.0, size=4)
print(z)

# truncation
print(np.trunc(z))

# fix
print(np.fix(z))

# rounding
print(np.around(z))

# floor
print(np.floor(z))

# ceil
print(np.ceil(z))

[7.44792174 4.24768777 8.50079729 7.33699658]
[7. 4. 8. 7.]
[7. 4. 8. 7.]
[7. 4. 9. 7.]
[7. 4. 8. 7.]
[8. 5. 9. 8.]


In [41]:
# Logs
a = np.arange(1, 10)

print(np.log2(a)) # log 2

print(np.log10(a)) # log 10

print(np.log(a)) # log base e

# other bases
log_func = np.frompyfunc(log, 2, 1)

print(log_func(100, 15))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
1.7005483074552052


In [47]:
# Summations - happens for n elements, addition is btwn two args
print(a)
print(b)
print(np.sum([a, b])) # sum numbers from all arrays
print(np.sum([a, b], axis = 1)) # sum numbers from each array
print(np.cumsum(a)) # cumulative sum

[4 1 1 1 8 6 2 2 0 1]
[0 0 7 0 7 3 9 6 2 3]
63
[26 37]
[ 4  5  6  7 15 21 23 25 25 26]


In [53]:
# Products
print(a)
print(np.prod(a)) # product of elements in array a
print(np.prod([a, b])) # product of elements in a, b
print(np.prod([a, b], axis = 1)) # product of each - axis = 1
print(np.cumprod([a, b], axis = 1)) # cumulative product


[4 1 1 1 8 6 2 2 0 1]
0
0
[0 0]
[[  4   4   4   4  32 192 384 768   0   0]
 [  0   0   0   0   0   0   0   0   0   0]]


In [58]:
# Differences
print(a)
print(np.diff(a)) # discrete difference - subtracting successive elements
print(np.diff(a, n=3)) # done thrice

[4 1 1 1 8 6 2 2 0 1]
[-3  0  0  7 -2 -4  0 -2  1]
[ -3   7 -16   7   6  -6   5]


In [63]:
# LCM

print(np.lcm(3, 4))
print(np.lcm.reduce(a)) # lcm of an array
print(np.lcm.reduce(np.arange(1, 10))) # lcm for elements btwn 1 - 10

12
0
2520


In [64]:
# GCD

print(np.gcd(3, 4))
print(np.gcd.reduce(a)) # lcm of an array
print(np.gcd.reduce(np.arange(1, 10))) # lcm for elements btwn 1 - 10

1
1
1


In [85]:
# Trig, sin(), cos(), tan()

pie = np.pi
print(pie)

print(np.sin(pie))

print(np.tan(90))

print(np.cos(a))

print(np.deg2rad(a)) # degrees to radians
print(np.rad2deg(a)) # radians to degrees

# arcs
print(np.arcsin(0.6))
print(np.arccos(0.6))
print(np.arctan(0.6))
# print(np.arcsin(z)) # arcs in np array

print(np.hypot(3, 4)) # hypotenues



3.141592653589793
1.2246467991473532e-16
-1.995200412208242
[-0.65364362  0.54030231  0.54030231  0.54030231 -0.14550003  0.96017029
 -0.41614684 -0.41614684  1.          0.54030231]
[0.06981317 0.01745329 0.01745329 0.01745329 0.13962634 0.10471976
 0.03490659 0.03490659 0.         0.01745329]
[229.18311805  57.29577951  57.29577951  57.29577951 458.3662361
 343.77467708 114.59155903 114.59155903   0.          57.29577951]
0.6435011087932844
0.9272952180016123
0.5404195002705842
5.0


In [96]:
# Hyperbolic functions - take radians produce sinh, cosh, tanh

print(np.sinh(a))
print(np.sinh(90))
print(np.cosh(a))
print(np.tanh(np.pi))

# angles
print(np.arcsinh(90))
print(np.arccosh(z))

[2.72899172e+01 1.17520119e+00 1.17520119e+00 1.17520119e+00
 1.49047883e+03 2.01713157e+02 3.62686041e+00 3.62686041e+00
 0.00000000e+00 1.17520119e+00]
6.102016471589204e+38
[2.73082328e+01 1.54308063e+00 1.54308063e+00 1.54308063e+00
 1.49047916e+03 2.01715636e+02 3.76219569e+00 3.76219569e+00
 1.00000000e+00 1.54308063e+00]
0.99627207622075
5.192987713658941
[2.69654462 2.12536888 2.82982949 2.68139994]


In [109]:
# Set operations - set is a collection of unique elements

print(f"A: {a}")
print(f"B: {b}")
set_a = np.unique(a) # creating a set

print(f"Set: {set_a}")

un_ab = np.union1d(a, b) # union of a, b
print(f"Union: {un_ab}")

int_ab = np.intersect1d(a, b, assume_unique=True) # intersection
print(f"Intersection: {int_ab}")

dif_ab = np.setdiff1d(a, b, assume_unique=True) # set difference
print(f"Set Difference: {dif_ab}")

sym_diff = np.setxor1d(a, b, assume_unique=True) # symmetric difference
print(sym_diff)

A: [4 1 1 1 8 6 2 2 0 1]
B: [0 0 7 0 7 3 9 6 2 3]
Set: [0 1 2 4 6 8]
Union: [0 1 2 3 4 6 7 8 9]
Intersection: [0 0 0 1 1 1 2 2 3 6 7]
Set Difference: [4 1 1 1 8 1]
[4 8 9]
