<a href="https://colab.research.google.com/github/lumunge/100-days-of-code/blob/master/Python/NumpyNotes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import numpy
import numpy as np # alias

In [16]:
arr = np.array([1, 2, 3, 4, 5])

In [14]:
arr1 = np.array((6, 4, 7, 8, 3))

In [10]:
# print(arr1)
# print(type(arr1))

[6 4 7 8 3]
<class 'numpy.ndarray'>


In [13]:
arr2 = np.array(20)   
# print(arr2)

In [18]:
arr3 = np.array([6, 8, 9, 3, 1, 7])
print(arr3)
print(type(arr3))

[6 8 9 3 1 7]
<class 'numpy.ndarray'>


In [15]:
arr4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
print(arr4.ndim)
print(arr5.ndim)

2
3


In [23]:
arr6 = np.array([-1], ndmin=5) # 5 dimensions
print(arr6)

[[[[[-1]]]]]


In [25]:
# ACCESSING ELEMENTS
print(arr[3])
print(arr[3] + arr1[-1])

3
6


In [29]:
print(arr4[0, 0], arr4[len(arr4) - 1, len(arr4) - 1])

1 9


In [30]:
# SLICING ARRAYS

# [start:end]
# [start:end:step]

In [ ]:
print(arr3)
print(arr3[2:-1])
print(arr3[3:]) # after
print(arr3[:3]) # before
print(arr3[-3:-1]) # negative slicing
print(arr3[1:6:2]) # step


In [50]:
# DATA TYPES
"""
i - (integer) b - (boolean) u - (unsigned integer) f - (float) 
c - complex float m - (timedelta) M - datetime O - object
S - string U - unicode string V - fixed memory
"""
 
print(arr4.dtype)

arr7 = np.array(['water', 'air', 'thunder'])
print(arr7.dtype)

# Creating with predefined types
arr8 = np.array(['water', 'air', 'thunder'], dtype='S') # 4-byte integers
print(arr8.dtype)


int64
<U7
|S7


In [56]:
arr9 = np.array([3.0, 5.6, 9.6, 4.1])
# arr10 = arr9.astype('i')
arr10 = arr9.astype(int)
# arr10 = arr9.astype(bool)
print(arr10)
print(arr10.dtype)

[3 5 9 4]
int64


In [57]:
# Copy and View
# Copy == new array, View == view of original array

In [65]:
# COPY
arr11 = np.array([1, 2, 3, 4, 5])
arr12 = arr11.copy()
arr11[0] = 66
# print(arr11)
# print(arr12)

In [62]:
# VIEW
arr13 = arr12.view()
arr11[0] = 77
# print(arr11)
# print(arr13)

In [67]:
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[6 4 7 3 5]


In [12]:
# SHAPE OF AN ARRAY -> This is the number of elements in each direction
arr14 = np.array([[1, 2, 3], [4, 5, 6]])
arr15 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr16 = np.array([6, 5, 4, 3, 2], ndmin = 5)

print(arr14.shape)
print(arr15.shape)
print(arr16.shape)

(2, 3)
(2, 2, 3)
(1, 1, 1, 1, 5)


In [29]:
# ARRAY RESHAPING -> changing the shape of an array
arr17 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr17.reshape(6, 2))
print(arr17.reshape(4, 3))
# 1D to 2D
print(arr17.reshape(2, 3, 2)) # 2 arrays, with 3 arrays, with two elements each

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [32]:
print(arr17.reshape(4, 3).base) # a view

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [54]:
# unknown dimension
arr18 = arr17.reshape(2, 2, -1) # can pass more than 1 dimension
print(arr18)
# Flattening
arr18.reshape(-1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
# Joining two arrays
arr19 = np.concatenate((arr3.reshape(-1), arr16.reshape(-1)))
print(arr19)

arr19a = np.array([[1, 2], [3, 4]])
arr19b = np.array([[5, 6], [7, 8]])

print(np.concatenate((arr19a, arr19b), axis = 1))

np.stack((arr19a, arr19b), axis = 1)

print("stack rows")
print(np.hstack((arr19a, arr19b)))

print("stack columns")
print(np.vstack((arr19a, arr19b)))

print("stack depth")
print(np.dstack((arr19a, arr19b)))

[6 8 9 3 1 7 6 5 4 3 2]
[[1 2 5 6]
 [3 4 7 8]]
stack rows
[[1 2 5 6]
 [3 4 7 8]]
stack columns
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
stack depth
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [126]:
# Splitting numpy arrays
print(arr19)
print(np.array_split(arr19, 3))
arr19c = np.array_split(arr19, 3)
print(arr19c[0])
print(arr19c[1])

# split along rows
print(np.array_split(arr18, 2, axis = 1))

# hsplit() -> split along rows
# hstack() -> split along columns
# vstack()
# dstack()
# vsplit()
# dsplit()

[6 8 9 3 1 7 6 5 4 3 2]
[array([6, 8, 9, 3]), array([1, 7, 6, 5]), array([4, 3, 2])]
[6 8 9 3]
[1 7 6 5]
[array([[[1, 2, 3]],

       [[7, 8, 9]]]), array([[[ 4,  5,  6]],

       [[10, 11, 12]]])]


In [152]:
# Finding elements -> Searching arrays
np.where(arr19 == 3)
print(arr19)
print(np.where(arr19 % 2 == 0)) # indexes of even values

# SearchSorted - binary search array, return index where value is inserted to maintaine order
print(arr19)

x = np.sort(arr19)
y = np.searchsorted(x, 7)
print(y)

z = np.searchsorted(x, 7, side='right')
a = np.searchsorted(x, 7, side='left')
print(z)
print(a)

b = np.searchsorted(x, [4, 8, 11])
print(b)


[6 8 9 3 1 7 6 5 4 3 2]
(array([ 0,  1,  6,  8, 10]),)
[6 8 9 3 1 7 6 5 4 3 2]
8
9
8
[ 4  9 11]


In [153]:
# Sort array
np.sort(arr19)

arr21 = np.array(['cook', 'peter', 'zed', 'academy'])
print(np.sort(arr21))



['academy' 'cook' 'peter' 'zed']


In [159]:
# Filtering arrays
fil21 = [True, False, True, False]

print(arr21[fil21])

# Create filter array
fil22 = []

for e in arr21:
  if(len(e) > 4):
    fil22.append(True)
  else:
    fil22.append(False)

print(arr21[fil22])

print(arr19)
fil23 = arr19 > 6
print(fil23)
print(arr19[fil23])

['cook' 'zed']
['peter' 'academy']
[6 8 9 3 1 7 6 5 4 3 2]
[False  True  True False False  True False False False False False]
[8 9 7]


In [83]:
# Iterating Arrays
# for x in arr19:
  # print(x)

# print(arr18)
# for x in arr18:
#   print(f"This: {x}")

# Iterate on each 2-D array
for x in arr18:
  for y in x:
    print(y)

# Single element 3D
for x in arr18:
  for y in x:
    for z in y:
      print(z)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [90]:
arr20 = np.array([[[1, 2], [7, 9]], [[5, 6], [3, 8]]])

# nditer -> helper function for iteration
for x in np.nditer(arr20):
  print(x)

1
2
7
9
5
6
3
8


In [97]:
# different data types iteration
# arr20

# for x in np.nditer(arr20, flags=['buffered'], op_dtypes=['S']):
#   print(x)

# Step sizes
# for x in np.nditer(arr20[:, ::2]):
#   print(x)

# Enumerated iteration
for x, y in np.ndenumerate(arr):
  print(x, y)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
